/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestiondeencomiendas;

/**
 *
 * @author HP-PROBOOK 640
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtxtUsuario = new javax.swing.JTextField();
        jbtnIngresar = new javax.swing.JButton();
        jlblUsuarioIcono = new javax.swing.JLabel();
        jpwdContrasena = new javax.swing.JPasswordField();
        jlblPassIcono = new javax.swing.JLabel();
        jlblTitulo = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jlblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inicio de sesión");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jtxtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 110, -1));

        jbtnIngresar.setText("Ingresar");
        getContentPane().add(jbtnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, 90, -1));

        jlblUsuarioIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/UserIcon.png"))); // NOI18N
        getContentPane().add(jlblUsuarioIcono, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 40, 50));
        getContentPane().add(jpwdContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, 110, -1));

        jlblPassIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconos/candado.png"))); // NOI18N
        getContentPane().add(jlblPassIcono, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 40, 50));

        jlblTitulo.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        jlblTitulo.setText("Inicio de sesión");
        getContentPane().add(jlblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 390, 60));
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 330, 60, 50));

        jlblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondos/loginFondo.png"))); // NOI18N
        getContentPane().add(jlblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jbtnIngresar;
    private javax.swing.JLabel jlblFondo;
    private javax.swing.JLabel jlblPassIcono;
    private javax.swing.JLabel jlblTitulo;
    private javax.swing.JLabel jlblUsuarioIcono;
    private javax.swing.JPasswordField jpwdContrasena;
    private javax.swing.JTextField jtxtUsuario;
    // End of variables declaration//GEN-END:variables
}
