/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestiondeencomiendas;

import java.awt.Color;

/**
 *
 * @author HP-PROBOOK 640
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipall
     */
    public MenuPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtxtTexto1 = new javax.swing.JLabel();
        jtxtTexto2 = new javax.swing.JLabel();
        jtxtTexto3 = new javax.swing.JLabel();
        jbtnSalir = new javax.swing.JButton();
        jtxtFondo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestor De Encomiendas");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(720, 430));
        setPreferredSize(new java.awt.Dimension(720, 430));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtxtTexto1.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jtxtTexto1.setForeground(new java.awt.Color(240, 240, 240));
        jtxtTexto1.setText("Gestor de encomiendas");
        getContentPane().add(jtxtTexto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 600, 100));

        jtxtTexto2.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jtxtTexto2.setForeground(new java.awt.Color(240, 240, 240));
        jtxtTexto2.setText("del edificio");
        getContentPane().add(jtxtTexto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 330, -1));

        jtxtTexto3.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jtxtTexto3.setForeground(new java.awt.Color(240, 240, 240));
        jtxtTexto3.setText("OurBike");
        getContentPane().add(jtxtTexto3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, -1, -1));
        getContentPane().add(jbtnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 330, 30, 20));

        jtxtFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondos/fondo.png"))); // NOI18N
        getContentPane().add(jtxtFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 390));

        jMenuBar1.setBackground(new java.awt.Color(0, 153, 204));
        jMenuBar1.setForeground(new java.awt.Color(240, 240, 240));

        jMenu1.setText("Ingresar");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Actualizar");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Eliminar");
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Listar");
        jMenuBar1.add(jMenu4);

        jMenu5.setText("Acerca de");
        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JButton jbtnSalir;
    private javax.swing.JLabel jtxtFondo;
    private javax.swing.JLabel jtxtTexto1;
    private javax.swing.JLabel jtxtTexto2;
    private javax.swing.JLabel jtxtTexto3;
    // End of variables declaration//GEN-END:variables
}
